spring:
  application:
    name: app-cache
  servlet:
    context-path: /app-cache
  cache:
    cache-names: cache1, cache2, cache3
  datasource:
    url: jdbc:h2:mem:ciudadesdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true