logging:
  level:
    root: INFO
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG

server:
  port: 8080
  servlet:
      context-path: /cache
spring:
  cache:
    infinispan:
      config: classpath:infinispan.xml
    cache-names: ciudadesCache, cache2, cache3
  datasource:
    url: jdbc:h2:mem:ciudadesdb
    username: sa
    password: 123
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
